# Basic Site Settings
title: Federico Martinez
email: federico@example.com
description: >-
  Hi! I'm Fede, welcome to my personal blog where I'll write about things I learn and find useful.
baseurl: "/"
url: "https://fedxgibson.github.io"

# Build settings
# theme: minima
permalink: /blog/:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social Media
github_username: fedxgibson
linkedin_username: federico-martinez-bertone
email: federico.martinez005@gmail.com

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/